# fly.toml app configuration file generated for writebackreminder on 2025-10-11T14:43:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'writebackreminder'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  # Persist user data to the mounted volume so conversations and recommendations
  # survive restarts and deploys.
  USER_DATA_DIR = '/data/userdata'
  RECOMMENDATIONS_DIR = '/data/userdata/recommendations'

[[mounts]]
  source = 'wbr_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
